//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetTransfer_
    {
        public int SNo { get; set; }
        public string AssetID { get; set; }
        public string AllocatedEmpID { get; set; }
        public string AllocatedEmpName { get; set; }
        public string AssignedByEmpID { get; set; }
        public string AssignedByName { get; set; }
        public Nullable<System.DateTime> AssignedDate { get; set; }
        public string Location { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
    }
}
