//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asset
    {
        public int SNo { get; set; }
        public string AssetID { get; set; }
        public string AllocatedEmployeeName { get; set; }
        public string AllocatedEmployeeID { get; set; }
        public string Location { get; set; }
        public string AllocatedStatus { get; set; }
        public string AssignedBy { get; set; }
        public string AssignedByEmpID { get; set; }
        public Nullable<System.DateTime> AssignedDate { get; set; }
        public string Remarks { get; set; }
        public string AssetType1 { get; set; }
        public string AssetType2 { get; set; }
        public string AssetType3 { get; set; }
        public string AssetType4 { get; set; }
        public string AssetType5 { get; set; }
        public string AssetType6 { get; set; }
        public string Manufacturer { get; set; }
        public string Model { get; set; }
        public string BarCode { get; set; }
        public string RAM { get; set; }
        public Nullable<System.DateTime> WarrantyStartDate { get; set; }
        public Nullable<System.DateTime> WarrantyEndDate { get; set; }
        public string AssetMainImage { get; set; }
        public string AssetType1Image { get; set; }
        public string AssetType2Image { get; set; }
        public string AssetType3Image { get; set; }
        public string AssetType4Image { get; set; }
        public string AssetType5Image { get; set; }
        public string AssetType6Image { get; set; }
        public string VendorName { get; set; }
        public string PONumber { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
