//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compoff
    {
        public int Compoff_no { get; set; }
        public string EmployeeID { get; set; }
        public System.DateTime CampOffDate { get; set; }
        public string EmployeeName { get; set; }
        public string HolidayName { get; set; }
        public string concatinatestring { get; set; }
        public string addStatus { get; set; }
        public string createdby { get; set; }
        public Nullable<System.DateTime> createddate { get; set; }
        public string updatedby { get; set; }
        public Nullable<System.DateTime> updateddate { get; set; }
        public Nullable<int> Holidayno { get; set; }
        public string Location { get; set; }
    }
}
