//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class con_leaveupdate
    {
        public int leaveno { get; set; }
        public Nullable<System.DateTime> leavedate { get; set; }
        public string employee_id { get; set; }
        public string leave_reason { get; set; }
        public string DayType { get; set; }
        public decimal LeaveDays { get; set; }
        public string HalfDayCategory { get; set; }
        public string submittedby { get; set; }
        public string leavesource { get; set; }
        public string leaveuniqkey { get; set; }
        public string leavecategory { get; set; }
        public string employee_name { get; set; }
        public string BackupResource_Name { get; set; }
        public string EmergencyContact_no { get; set; }
        public string LeaveStatus { get; set; }
        public string OfficalEmailid { get; set; }
        public Nullable<System.DateTime> Fromdate { get; set; }
        public Nullable<System.DateTime> Todate { get; set; }
        public string LeaveRequestName { get; set; }
        public string Location { get; set; }
        public string createdby { get; set; }
        public Nullable<System.DateTime> createddate { get; set; }
        public string updatedby { get; set; }
        public Nullable<System.DateTime> updateddate { get; set; }
        public string Designation { get; set; }
    }
}
