//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class emp_info
    {
        public int Sno { get; set; }
        public string EmployeeID { get; set; }
        public string EmployeeStatus { get; set; }
        public string EmployeeName { get; set; }
        public string FatherName { get; set; }
        public string Gender { get; set; }
        public string BloodGroup { get; set; }
        public System.DateTime DOB { get; set; }
        public System.DateTime DOJ { get; set; }
        public string Age { get; set; }
        public string MaritalStatus { get; set; }
        public string Designation { get; set; }
        public string ShiftTimings { get; set; }
        public string Department { get; set; }
        public string Client { get; set; }
        public string EmployeeType { get; set; }
        public string Location { get; set; }
        public string ReportingManager { get; set; }
        public string LeavereportingManager { get; set; }
        public string MobileNumber { get; set; }
        public string Personal_Emailid { get; set; }
        public string OfficalEmailid { get; set; }
        public string PresentAddress { get; set; }
        public string Permanent_Address { get; set; }
        public string RelationName { get; set; }
        public string Relationship { get; set; }
        public string FamilyMobileNumber { get; set; }
        public string BankName { get; set; }
        public string AccountNumber { get; set; }
        public string Branch { get; set; }
        public string TypeofAccount { get; set; }
        public string IFSCcode { get; set; }
        public string PANnumber { get; set; }
        public string AadharNumber { get; set; }
        public string Passport { get; set; }
        public Nullable<System.DateTime> DOEofPassport { get; set; }
        public string UANNumber { get; set; }
        public string PFNumber { get; set; }
        public string ESICNumber { get; set; }
        public string LatestDegree { get; set; }
        public string College_Name { get; set; }
        public string Specialization { get; set; }
        public Nullable<int> YearofCompletion { get; set; }
        public string Employer_name { get; set; }
        public string JobTitle { get; set; }
        public Nullable<System.DateTime> From_date { get; set; }
        public Nullable<System.DateTime> To_date { get; set; }
        public string ReasonforRelieving { get; set; }
        public Nullable<System.DateTime> DateofExit { get; set; }
        public string Reason { get; set; }
        public string EligibleforRehire { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string imagepath { get; set; }
        public Nullable<System.TimeSpan> ShiftStartTime { get; set; }
        public Nullable<System.TimeSpan> ShiftEndTime { get; set; }
        public string Roles_Responsibilities { get; set; }
        public string Client1 { get; set; }
        public string ProjectName1 { get; set; }
        public string Role1 { get; set; }
        public string ReportingManager1 { get; set; }
        public string Client2 { get; set; }
        public string ProjectName2 { get; set; }
        public string Role2 { get; set; }
        public string ReportingManager2 { get; set; }
        public string Client3 { get; set; }
        public string ProjectName3 { get; set; }
        public string Role3 { get; set; }
        public string ReportingManager3 { get; set; }
    }
}
