//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class emp_info2
    {
        public int Sno { get; set; }
        public string EmployeeID { get; set; }
        public string EmployeeName { get; set; }
        public string FatherName { get; set; }
        public System.DateTime DOJ { get; set; }
        public System.DateTime DOB { get; set; }
        public int Age { get; set; }
        public string BloodGroup { get; set; }
        public string EmployeeStatus { get; set; }
        public string Gender { get; set; }
        public string MaritalStatus { get; set; }
        public string Designation { get; set; }
        public string Department { get; set; }
        public Nullable<System.TimeSpan> ShiftTiming { get; set; }
        public string Client { get; set; }
        public string EmployeeType { get; set; }
        public string Location { get; set; }
        public string AMBCReporting_Manager { get; set; }
        public string LeavereportingManager { get; set; }
        public string MobileNumber { get; set; }
        public string PersonalEmail_id { get; set; }
        public string OfficalEmailID { get; set; }
        public string PresentAddress { get; set; }
        public string PermanentAddress { get; set; }
        public string BankName { get; set; }
        public string AccountNumber { get; set; }
        public string Branch { get; set; }
        public string TypeofAccount { get; set; }
        public string IFSCCode { get; set; }
        public string PANNumber { get; set; }
        public string AadharNumber { get; set; }
        public string PassportNo { get; set; }
        public Nullable<System.DateTime> DOEofPassport { get; set; }
        public string UANNumber { get; set; }
        public string PFNumber { get; set; }
        public string ESICNumber { get; set; }
        public string LatestDegree { get; set; }
        public string CollegueName { get; set; }
        public int Yearofcompletion { get; set; }
        public string EmployerName { get; set; }
        public string JobTitle { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public string ReasonforRelieving { get; set; }
        public Nullable<System.DateTime> DateofExit { get; set; }
        public string Reason { get; set; }
        public string EligibleforRehire { get; set; }
    }
}
