//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class emplogin1
    {
        public string EmployeeID { get; set; }
        public string EmployeeName { get; set; }
        public string Password { get; set; }
        public string EmployeeEmail { get; set; }
        public string EmployeeStatus { get; set; }
        public string EmployeeMobile { get; set; }
        public string EmployeeRole { get; set; }
        public string EmloyeeSysHostname { get; set; }
        public string EmployeeLogininfo { get; set; }
    }
}
