//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeBasedClient
    {
        public int Sno { get; set; }
        public string EmployeeID { get; set; }
        public string EmployeeName { get; set; }
        public string OfficalEmailid { get; set; }
        public string EmployeeStatus { get; set; }
        public string Client { get; set; }
        public string ProjectName { get; set; }
        public string Role1 { get; set; }
        public string ReportingManager { get; set; }
    }
}
