//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobDetail
    {
        public int JobID { get; set; }
        public string JobTitle { get; set; }
        public string Experience { get; set; }
        public string Location { get; set; }
        public string PostedBy { get; set; }
        public Nullable<System.DateTime> PostedDate { get; set; }
        public string JobType { get; set; }
        public string JobStatus { get; set; }
        public string SalaryRange { get; set; }
        public string Priority { get; set; }
        public string JobDescription { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
