//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveRM
    {
        public int Sno { get; set; }
        public string Name { get; set; }
        public Nullable<bool> IsLeaveRM { get; set; }
        public Nullable<bool> IsReporingM { get; set; }
    }
}
