//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int SNo { get; set; }
        public Nullable<System.DateTime> NotificationDate { get; set; }
        public string NotificationFromName { get; set; }
        public string NotificationFromID { get; set; }
        public string NotificationToName { get; set; }
        public string NotificationToID { get; set; }
        public string NotificationType { get; set; }
        public string ReferenceNumber { get; set; }
        public string Status { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
