//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseRequest
    {
        public int PurchaseRequestID { get; set; }
        public string AssetType { get; set; }
        public string RequestedBy { get; set; }
        public Nullable<System.DateTime> RequiredOn { get; set; }
        public int VendorID1 { get; set; }
        public string VendorName1 { get; set; }
        public string VendorEmail1 { get; set; }
        public decimal QuotationPrice1 { get; set; }
        public string AttachFile1 { get; set; }
        public Nullable<int> VendorID2 { get; set; }
        public string VendorName2 { get; set; }
        public string VendorEmail2 { get; set; }
        public Nullable<decimal> QuotationPrice2 { get; set; }
        public string AttachFile2 { get; set; }
        public Nullable<int> VendorID3 { get; set; }
        public string VendorName3 { get; set; }
        public string VendorEmail3 { get; set; }
        public Nullable<decimal> QuotationPrice3 { get; set; }
        public string AttachFile3 { get; set; }
        public string Status { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public string RejectedBy { get; set; }
        public Nullable<System.DateTime> RejectedDate { get; set; }
        public string PO { get; set; }
        public string TaxInvoice { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string PRNumber { get; set; }
    }
}
