//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subscription
    {
        public int SubscriptionID { get; set; }
        public string SubscriptionName { get; set; }
        public string SubscriptionLogo { get; set; }
        public string Category { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public Nullable<System.DateTime> RenewalDate { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string PaymentMethod { get; set; }
        public string Remarks { get; set; }
        public string SubscriptionStatus { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string License { get; set; }
        public int UniqueSubscriptionID { get; set; }
        public Nullable<System.DateTime> NewPurchaseDate { get; set; }
        public Nullable<System.DateTime> NewRenewalDate { get; set; }
        public Nullable<decimal> NewAmount { get; set; }
        public string NewPaymentMethod { get; set; }
        public string NewRemarks { get; set; }
        public string NewSubscriptionStatus { get; set; }
        public string NewCreatedBy { get; set; }
        public Nullable<System.DateTime> NewCreatedDate { get; set; }
        public string NewLicense { get; set; }
    }
}
