//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeSheet
    {
        public int TimeSheetID { get; set; }
        public string Client { get; set; }
        public string EmployeeID { get; set; }
        public string EmployeeName { get; set; }
        public string EmployeeEmail { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Category { get; set; }
        public string IncidentTaskName { get; set; }
        public string IncidentTaskDescription { get; set; }
        public string Requester { get; set; }
        public Nullable<decimal> HoursSpent { get; set; }
        public string Priority { get; set; }
        public string Status { get; set; }
        public string CreateddBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> WeekNo { get; set; }
        public string submissionstatus { get; set; }
    }
}
